### ISSUE TITLE
"reload" is never called

### ISSUE THREAD

**Issue by niksy** [skyrpex/vue-jsx-hot-loader#12]
When I’m changing data other than `render` method, HMR registers change, but nothing is applied to changed module. It seems like Hot API `reload` method should be called but it isn’t. Changing only `render` method successfully runs `rerender` method. Is this something related to serializing JS object?

**Comment by skyrpex** [comment]
It currently works to me on v1.1.3... could you please provide a minimal example?

**Comment by skyrpex** [comment]
I'll close this until I can reproduce the problem. Feel free to reopen it with an example 👍
