### ISSUE TITLE
Usage of lodash `isNative()` prevents usage of `babel-polyfill`

### ISSUE THREAD

**Issue by nddery** [skyrpex/vue-jsx-hot-loader#13]
Lodash `isNative()` ([and the entire library in v5.0](https://github.com/lodash/lodash/commit/e156459176c1f35964fc443b39f04c4cb0a96763#commitcomment-17483142)) triggers an error when the host project uses `core-js`.

This is somewhat unexpected and breaks application using `babel-preset-env` with `babel-polyfill`.

I'm not sure what the solution is, adding a note in the README or not using lodash entirely..

**Comment by skyrpex** [comment]
Perfect timing! I just was encountering this error:

![image](https://user-images.githubusercontent.com/1077520/27738154-dbc35970-5daa-11e7-8ce1-8cd89d10a9eb.png)

I'll try to use a custom method to remove native types before serializing.

**Comment by skyrpex** [comment]
This should be fixed now in v1.1.4. This version also fixes serializing cyclic objects.
