### ISSUE TITLE
api.rerender() doesn't work when using components with slots

### ISSUE THREAD

**Issue by skyrpex** [skyrpex/vue-jsx-hot-loader#14]
## Error

Vue Hot Reload API doesn't work as expected when using `api.rerender()` on a component that uses slots.

```jsx
export default {
  render() {
    return (
      <button>
        {/* Try adding and then removing the TEST text. It won't be removed, just added as many times as you save. */}
        {this.$slots.default} TEST 
      </button>
    );
  },
};
```

## How to reproduce

`npm run test:webpack` will start a development server. Go to [tests\webpack\src\nativeModules\button.jsx](https://github.com/skyrpex/vue-jsx-hot-loader/blob/9ea57f597dd78cb4964d368273784dcd91f1c22e/tests/webpack/src/nativeModules/button.jsx#L11-L15), add / remove the TEST text and save.

## Workaround

Wrap your slots inside another node (like a span):

```jsx
export default {
  render() {
    return (
      <button>
        <span>
          {this.$slots.default}
        </span>
        {/* You're safe editing this */
        TEST
      </button>
    );
  },
};
```

## Notes

`api.reload()` works as expected (the whole component gets rerendered).

**Comment by nddery** [comment]
This seems like a bug in Vue `vm.$forceUpdate()` method - https://jsfiddle.net/5k4ptmqg/87/ (after 1 second `$forceUpdate` is called and the bug is seen)

I'll open an issue over there.

**Comment by nddery** [comment]
Seems like this was fixed (at least for templates) in 2.1.5, the release notes mentions:

> Small across-the-board performance improvement for render functions compiled from templates. **They now skip the normalization of nested children arrays based on information inferred from the templates at compile time.**

However, this issue still persists when using render function (hence JSX), and potentially `.vue` files also ?

**Comment by skyrpex** [comment]
Thanks for finding where the error is. Did you finally create an issue in Vue's repository?

**Comment by skyrpex** [comment]
Looks like this problem is already fixed in new versions of Vue :+1:
