### ISSUE TITLE
Usage with TypeScript

### ISSUE THREAD

**Issue by chmln** [skyrpex/vue-jsx-hot-loader#19]
Hello,

Thank you so much for your work on this. 👊 👊 👊 
Only after migrating to class components I found out hot reloading was broken, this is such a lifesaver.

Just a heads up that this loader works with typescript too.
```ts
{
        test: /\.tsx$/,
        use: [
          { loader: "babel-loader" },
          { loader: 'vue-jsx-hot-loader'},
          {  loader: "ts-loader",  },
        ],
}
```

**Comment by skyrpex** [comment]
Thanks for the heads up! I'm glad it works for you.

**Comment by skyrpex** [comment]
I think that @nddery and @deadNightTiger should also see this, since they contributed a lot :)
