### ISSUE TITLE
Doesn't work with webpack 4

### ISSUE THREAD

**Issue by deadNightTiger** [skyrpex/vue-jsx-hot-loader#20]
Looks like webpack 4 replaces global `this` to `undefined` in ES6 modules, so `ctx` is always `undefined` here: https://github.com/skyrpex/vue-jsx-hot-loader/blob/develop/src/api.js#L23

As a workaround, we could change `ctx: this` to `ctx: eval('this')` in the code appended by the loader.

**Comment by skyrpex** [comment]
Thanks, tiger. Released v1.3.0.
