### ISSUE TITLE
Whether `tsx` and `vue-class-component` support?

### ISSUE THREAD

**Issue by ZSkycat** [skyrpex/vue-jsx-hot-loader#24]

**Comment by deadNightTiger** [comment]
Yes, that's how I use it. Do you have a specific problem?

**Comment by ZSkycat** [comment]
Does not seem to support jsx and templates mixed use.

Use case repository
https://github.com/ZSkycat/issue-vue-jsx-hot-loader-20180831

**Comment by skyrpex** [comment]
Sorry, I didn't see the issue. I think that the problem lies in the order of the loaders.

https://github.com/ZSkycat/issue-vue-jsx-hot-loader-20180831/blob/ee18ab173e457ac4315fadc159aa19f6e355344b/webpack.config.js#L48-L58

You should put the 'vue-jsx-hot-loader' at the end, after TypeScript code is converted into Javascript. Like this:

```js
 {
    test: /\.tsx$/,
    use: [
        'babel-loader',
        {
            loader: 'ts-loader',
            options: { appendTsxSuffixTo: [/\.vue$/], compilerOptions: { sourceMap: true } },
        },
        'vue-jsx-hot-loader',
    ],
},
```

**Comment by skyrpex** [comment]
Anyway, I'm using your project and the hot reloading is correctly working to me.

What's the problem you're experiencing?

**Comment by ZSkycat** [comment]
I don't know what happened. I tried it again and it worked correctly. 😅

**Comment by deadNightTiger** [comment]
@ZSkycat maybe they fixed something in vue-loader since you reported this, because I remember there was some incompatibilities.

**Comment by skyrpex** [comment]
Well, great then! 👏

**Comment by chanlito** [comment]
Quick question, how'd I configure this with Vue CLI 3?

**Comment by skyrpex** [comment]
Oh, I was looking now at the source of the Vue CLI in order to solve your issue.

Thanks to you for writing the solution! I'll add the Vue CLI integration example to the readme.

**Comment by skyrpex** [comment]
Maybe there's room for a JSX HMR Vue CLI plugin...
