### ISSUE TITLE
Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by ArmorDarks** [skyrpex/vue-jsx-hot-loader#25]
Thanks for the loader, it works nicely!

However, there is an error occurs when the loader used:

![h4ciT3U](https://user-images.githubusercontent.com/4460311/58385614-be6f6100-7ffb-11e9-9432-c17cd0130bad.png)

Hot Reloading works as intended, but that error will simply reoccur with each file save.

Error is happening here, in Vue script:

![2019-05-26_21-19-02](https://user-images.githubusercontent.com/4460311/58385628-ef4f9600-7ffb-11e9-9c2b-405d9bd9e493.png)

Seems like Vue does not like some loader changes, however it can't log an error about it properly since `key` in that case results to be `Symbol`...

**Comment by skyrpex** [comment]
You're welcome 😄

I've never encountered this error myself. Could you provide a code example or repository?

**Comment by ArmorDarks** [comment]
[Here we go](https://github.com/ArmorDarks/vue-jsx-symbol-error).

I've tried to reduce my current project to the minimal repo. Run `npm start` to run the server and open http://localhost:8080

I thought that it might be related to the Vue class decorators or metadata polyfill, but primarily tests shown no difference.

**Comment by deadNightTiger** [comment]
I think you forgot to include an html file in your reproduction, as it gives 404 on `http://localhost:8080/` :)

**Comment by ArmorDarks** [comment]
Ops, that was stupid. I've forgotten that it's ignored by default. Fixed.

**Comment by skyrpex** [comment]
Looks like Lodash throws an error when trying to detect the type of the Vue proxy objects. Not sure where do they come from exactly, but I'm just ignoring these objects from the serialization anyway.

Please, check out the 1.4.1 release: https://github.com/skyrpex/vue-jsx-hot-loader/releases/tag/v1.4.1

**Comment by ArmorDarks** [comment]
Yeap, fixed. Thanks a lot!
