### ISSUE TITLE
Thoughts and suggestions

### ISSUE THREAD

**Issue by niksy** [skyrpex/vue-jsx-hot-loader#3]
First of all, thanks for this loader! I have some thoughts and suggestions for this loader:

* Maybe rename it to something more descriptive like `vue-jsx-hot-loader`? This way it seems like it handles JSX transformations although there is already Babel plugin which does that
* Publish it as unscoped module
* Handle situations where module doesn’t only have `render` method but also other methods like `data` - currently only `rerender` method is called but in more complex situations `reload` should be called - maybe check if component options has some other methods other than `render` and the switch to `reload` API call?
* Handle CJS exports - currently loader expects to have component options on `default` property of `module.exports` which is the case with ES modules, but it should also handle standard CJS exports (maybe also do check like for `rerender`/`reload` method)
* Coordinate with VueJS organization to make this loader official?

What do you think?

**Comment by skyrpex** [comment]
Hi! You're welcome :)

> Maybe rename it to something more descriptive like vue-jsx-hot-loader? This way it seems like it handles JSX transformations although there is already Babel plugin which does that

You're totally right. Will do.

> Publish it as unscoped module
> Coordinate with VueJS organization to make this loader official?

The reason I scoped the module was because it was an experiment. It'd be cool if the package ends being official :+1:

> Handle situations where module doesn’t only have render method but also other methods like data - currently only rerender method is called but in more complex situations reload should be called - maybe check if component options has some other methods other than render and the switch to reload API call?
> Handle CJS exports - currently loader expects to have component options on default property of module.exports which is the case with ES modules, but it should also handle standard CJS exports (maybe also do check like for rerender/reload method)

Those are good improvements. Will have to invest some time into learning how the internals work since I never got it at all (and it's being a long time since I created this plugin).
