### ISSUE TITLE
Doesn't seem to work when module: false is set in babel-preset-env (or babel-preset-es2015)

### ISSUE THREAD

**Issue by nddery** [skyrpex/vue-jsx-hot-loader#6]
I'm trying to make HMR works along with Webpack 2 treeshaking, which requires to set `module: false` for the `env` babel preset. However, this seems to break this loader, and result in the following error in `api.js` at line 46:

```js
Uncaught TypeError: Cannot read property '__esModule' of undefined
    at exports.default (eval at <anonymous> (build.js:953), <anonymous>:46:33)
    at Object.eval (eval at <anonymous> (build.js:1012), <anonymous>:39:34)
    at eval (eval at <anonymous> (build.js:1012), <anonymous>:40:30)
    at Object.<anonymous> (build.js:1012)
    at __webpack_require__ (build.js:660)
    at fn (build.js:86)
    at Object.eval (eval at <anonymous> (build.js:979), <anonymous>:3:63)
    at eval (eval at <anonymous> (build.js:979), <anonymous>:14:30)
    at Object.<anonymous> (build.js:979)
    at __webpack_require__ (build.js:660)
```

Seems like `module.exports` is undefined.. 

```js
// Retrieve the exported component. Handle ES and CJS modules.
var component = module.exports.__esModule ? module.exports.default : module.exports;
```

Looking at `module`, `exports` is effectively `undefined`, but there is an object on `module.__proto__.exports`.. I'm not too familiar with what Webpack does exactly under the hood.. 

With `module: false`:

```js
Object {exports: undefined, webpackPolyfill: 1}
```

With `module: false` **not** set:

```js
Object {i: 38, l: false, exports: Object, hot: Object, parents: Array(1)…}
```

My `.babelrc` is as follow:

```
{
  "presets": [
    ["env", { "modules": false }]
  ],
  "plugins": [
    "transform-vue-jsx"
  ]
}
```

Removing the `modules: false` part fix the issue - but I'd like to keep it to benefits from treeshaking.

**edit** I'd like to help but have no idea where to start.. I've found [this issue](https://github.com/webpack/webpack/issues/1885) but not sure how to apply it here or if it's really related.. Also, I can push a repo up showing this issue if you'd like (base vue webpack-simple starter with JSX and HMR).

**Comment by skyrpex** [comment]
I open up the issue until we decide what to do with this :+1:
